### ISSUE TITLE
Unsupported in ChaiNNer

### ISSUE THREAD

**Issue by KhanShahswar** [starinspace/StarinspaceUpscale#1]
2xVHS2HD-RealPLKSR.pth Unsupported in ChaiNNer. Is there a way fix this issue?

**Comment by starinspace** [comment]
![image](https://github.com/user-attachments/assets/3cf36ab3-3f9f-463a-b9d4-a7b1765aacae)

You need latest [Chainner Alpha v.0.24.1](https://github.com/chaiNNer-org/chaiNNer/releases/tag/v0.24.1), for it to work, however I have a ONNX version if you don't have possible to update.

[2xVHS2HD-RealPLKSR.onnx](https://mega.nz/file/UqhwhaJb#6-JqWo1w3hCt0438dAU5u2LNM0D2tL1hpPpcTp3Adys)

Tell me if this fix the problem.

**Comment by instant-high** [comment]
Link to ONNX version broken.
Can you please re-upload again?

Regards
Thomas

**Comment by starinspace** [comment]
> Link to ONNX version broken. Can you please re-upload again?
> 
> Regards Thomas

If you have the latest ChaiNNer, you can use the original 2xVHS2HD-RealPLKSR.pth model:
[GitHub Release - StarinspaceUpscale](https://github.com/starinspace/StarinspaceUpscale/releases/tag/Models)

If you still need the ONNX version, you can temporarily download it here:
[Download ONNX Model via Mega](https://mega.nz/file/Zi4WiT7B#BUd1tUBlziM6_IyHXSXRRcEB_SGYwmgP8t3fIyQE2i8)

**Comment by instant-high** [comment]
Thanks for the download link.

Saved me a lot of work converting to onnx / finding torch model code for converting

**Comment by starinspace** [comment]
> 2xVHS2HD-RealPLKSR.pth Unsupported in ChaiNNer. Is there a way fix this issue?

> Thanks for the download link.
> 
> Saved me a lot of work converting to onnx / finding torch model code for converting

As there seems to be an interest in the ONNX file format, I have published it here on GitHub so it does not disappear!

https://github.com/starinspace/StarinspaceUpscale/releases/tag/Models
